# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='male', max_length=10),
        ),
    ]
